# Generated by Django 3.1.2 on 2020-10-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elec_semlali_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Adress', models.TextField(max_length=400)),
                ('number', models.CharField(max_length=10)),
                ('fix', models.CharField(max_length=10)),
                ('Dription', models.CharField(max_length=500)),
                ('faceBook', models.URLField(max_length=450)),
                ('twitter', models.URLField(max_length=450)),
                ('google_plus', models.URLField(max_length=450)),
                ('linkdin', models.URLField(max_length=450)),
            ],
        ),
    ]
