# Generated by Django 3.1.2 on 2020-10-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elec_semlali_info',
            old_name='Dription',
            new_name='Description',
        ),
        migrations.AlterField(
            model_name='elec_semlali_info',
            name='fix',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='elec_semlali_info',
            name='number',
            field=models.CharField(max_length=40),
        ),
    ]
