# Generated by Django 3.1.2 on 2020-10-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20201018_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='elec_semlali_info',
            name='Web_site_Name',
            field=models.CharField(default='Elac Semlali', max_length=100),
            preserve_default=False,
        ),
    ]
