# Generated by Django 3.1.2 on 2020-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRD_added_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
