# Generated by Django 3.1.2 on 2020-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product_prd_added_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-PRD_added_at']},
        ),
        migrations.AlterField(
            model_name='tags',
            name='Type',
            field=models.CharField(blank=True, choices=[('NOUVEAU', 'NOUVEAU'), ('SOLDE', 'SOLDE'), ('BONNE_AFAIREeeeeeeeeeeeeee', 'BONNE AFAIRE'), ('EXCLUSIVE', 'EXCLUSIVE')], max_length=50, null=True),
        ),
    ]
