# Generated by Django 3.1.2 on 2020-10-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20201024_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='Type',
            field=models.CharField(blank=True, choices=[('NOUVEAU', 'NOUVEAU'), ('SOLDE', 'SOLDE'), ('BONNE_AFAIRE', 'BONNE AFAIRE'), ('EXCLUSIVE', 'EXCLUSIVE')], max_length=50, null=True),
        ),
    ]
